name: Daily Job Alerts

on:
  schedule:
    - cron: '30 6 * * *'  # Runs daily at 12:00 PM IST (06:30 UTC)
  workflow_dispatch:
  

jobs:
  job-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run job scraper
        id:  scraper_output
        run: |
          python job_scraper.py > jobs.txt
          echo "jobs<<EOF" >> $GITHUB_OUTPUT
          cat jobs.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  


      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Daily QA/Software Testing Job Alerts"
          to: ${{ secrets.TO_EMAIL }}
          from: "Daily Job Bot"
          secure: true
          body: |
            ${{ steps.scraper_output.outputs.jobs }}
